name: tidb-ai-integration-test

services:
  tidb:
    image: wangdi4zm/tind:v7.5.3-vector-index
    restart: always

  redis:
    image: redis:6.0.16
    restart: always

  backend:
    image: tidbai/backend:${E2E_DOCKER_TAG}
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:80"
    env_file:
      - .env.compose
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  frontend:
    image: tidbai/frontend:${E2E_DOCKER_TAG}
    restart: always
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      BASE_URL: http://backend
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"

  background:
    image: tidbai/backend:${E2E_DOCKER_TAG}
    restart: always
    depends_on:
      - redis
    ports:
      - "5555:5555"
    env_file:
      - .env.compose
    command: /usr/bin/supervisord
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "6"
